services:
  # --- ENTORNO LOCALHOST ---
  web-localhost-01:
    build: ./WEB01
    container_name: web-localhost-01
    ports:
      - "4001:80"
    networks:
      - red-publica

  bd-localhost:
    image: mysql:8.0
    container_name: bd-localhost
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laboratorio_db
    ports:
      - "4003:3306"
    networks:
      - red-privada

  # --- ENTORNO DEV ---
  web-dev-01:
    build: ./WEB02
    container_name: web-dev-01
    ports:
      - "5001:80"
    networks:
      - red-publica

  bd-dev:
    image: mysql:8.0
    container_name: bd-dev
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laboratorio_db
    ports:
      - "5003:3306"
    networks:
      - red-privada

networks:
  red-publica:
    driver: bridge
  red-privada:
    driver: bridge